### ISSUE TITLE
Setup development environment section

### ISSUE THREAD

**Issue by v-ctiutiu** [digitalocean/k8s-adoption-journey#10]
## Overview

This section should deal with the following topics:

- [x] Choosing the right cluster size.
- [x] Cluster creation steps.
- [ ] Install/configure ArgoCD.
- [x] Setup ingress.
- [x] Setup observability (logging, monitoring, alerting, etc).

**Note:**

In practice, it's recommended to have a dedicated cluster to host ArgoCD. For the sake of this guide, and to have every environment self contained, I would suggest to have a dedicated ArgoCD instance per env. This way, if users do not want to spend extra money just to test the upper envs, one can stay with a single env in the first phase, and then move to the next level if desired.

**Comment by v-bpastiu** [comment]
Work has been done in: https://github.com/digitalocean/k8s-adoption-journey/pull/24
The ArgoCD installation and configuration will be done in a different ticket.
