### ISSUE TITLE
GitOps repository layout

### ISSUE THREAD

**Issue by v-ctiutiu** [digitalocean/k8s-adoption-journey#13]
## Overview

The sample application GitHub repository needs to be prepared and aligned with GitOps practices, before implementing CI/CD.

Example Kustomize layout for multiple environments:

```text
.
├── base
│   └── resources
│       ├── cert-manager-issuer.yaml
│       ├── deployment.yaml
│       ├── ingress-host.yaml
│       ├── namespace.yaml
│       └── service.yaml
├── development
│   └── kustomization.yaml
├── production
│   └── kustomization.yaml
└── staging
    └── kustomization.yaml
```

Base folder contains all common resources for all environmenst. Then, environment specific overlays are applied via:

1. `development/kustomization.yaml`
2. `production/kustomization.yaml`
3. `staging/kustomization.yaml`

**Comment by v-bpastiu** [comment]
Final repository layout available here:
https://github.com/digitalocean/kubernetes-sample-apps/tree/master/microservices-demo
