### ISSUE TITLE
Getting started section (aka Setup)

### ISSUE THREAD

**Issue by v-ctiutiu** [digitalocean/k8s-adoption-journey#2]
## Overview

Getting started section should deal with the following topics:

- [x] Setting up a DOKS cluster.
- [x] Setting up a DOCR repository for custom applications images.
- [x] Setting up required tools to connect and explore the DOKS cluster (e.g. kubectl, helm).
- [x] Deploying a sample application and testing the setup.

**Comment by v-bpastiu** [comment]
Work done in:
https://github.com/digitalocean/k8s-adoption-journey/pull/15
