### ISSUE TITLE
Instructions are lacking for referring to the correct container registry in various `kustomization.yaml` files

### ISSUE THREAD

**Issue by boumanb** [digitalocean/k8s-adoption-journey#38]
The various `kustomization.yaml` files located [here](https://github.com/digitalocean/kubernetes-sample-apps/tree/master/microservices-demo/kustomize) contain references to `newName: registry.digitalocean.com/microservices-demo/cartservice` which is the container registry in DO from which to retrieve the various images from. However, the user, when following instructions correctly, has setup his very own container registry in DO. Inexperienced users will fail to bypass this "obstacle" and will get stuck since it's required to complete the [deploy staging chapter](https://github.com/digitalocean/k8s-adoption-journey/blob/main/docs/03-staging/deploying-the-online-boutique-sample-application-staging.md#bootstrap-the-online-boutique-application-using-kustomize).

I suggest to include a step in the journey that instructs to correct the references to the registry. I'd suggest to do the same for the `tilt-resources/dev/tilt_config.json` file that has the same reference.

**Comment by v-ctiutiu** [comment]
@boumanb 

Thanks for reporting the issue. We are aware of this aspect. 

The initial decision was to go this route and try to avoid using so many placeholders in each chapter. A note is left where appropriate, telling users about the internal naming convention used (here is such an [example](https://digitalocean.github.io/k8s-adoption-journey/02-development/setup-doks-dev/#provisioning-a-development-doks-cluster-for-microservices)). Just imagine the outcome for each chapter - hey replace this placeholder, then replace the following one, and so on. Also, jumping too much between chapters is not a fun experience. We try to keep everything fluid, if that makes sense. 

On the other hand, you're right. It seems that I forgot to leave a note in other related chapters (and dependent assets). Will take care of this aspect as soon as possible.

Thanks for checking.

**Comment by v-ctiutiu** [comment]
Should be fixed via #42.
