### ISSUE TITLE
[Building and pushing images with Cloud Native Buildpacks] where's make-cnb-docker-images.sh ? 

### ISSUE THREAD

**Issue by francis-jjk** [digitalocean/k8s-adoption-journey#44]
https://digitalocean.github.io/k8s-adoption-journey/01-getting-started/building-and-pushing-docker-images/building-and-pushing-images-using-cnb/

A helper script is used to ease the process, named [make-cnb-docker-images.sh](https://github.com/digitalocean/kubernetes-sample-apps/blob/master/microservices-demo/release-scripts/make-cnb-docker-images.sh).

point to 404

**Comment by v-ctiutiu** [comment]
@francis-jjk The `make-cnb-docker-images.sh` script is available in this [PR](https://github.com/digitalocean/kubernetes-sample-apps/pull/45). It was supposed to be merged yesterday but we encountered some issues with the script. We're working on delivering the  `make-cnb-docker-images.sh` script today.

Thanks.

**Comment by v-bpastiu** [comment]
We wil push this today @francis-jjk. Thanks for the patience.

**Comment by v-bpastiu** [comment]
Hello there, we have merged everything related to the Cloud Native Buildpacks. Can you please try again and update here.
